In [1]:
import torch

In [13]:
def to_onehot(y,num_classes):
    y_onehot = torch.zeros (y.size(0),num_classes)
    y_onehot.scatter_(1,y.view(-1,1).long(),1).float()
    return y_onehot


In [14]:
y= torch.tensor([0,1,2,0])
y_enc = to_onehot(y,3)
y_enc

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.]])

In [15]:
Z = torch.tensor( [[-0.2,  -0.5, -0.52],
                   [-0.2,  -0.1, -0.51],
                   [-0.3,  -0.4, -0.53],
                   [-0.39, -0.8, -0.54]])

Z

tensor([[-0.2000, -0.5000, -0.5200],
        [-0.2000, -0.1000, -0.5100],
        [-0.3000, -0.4000, -0.5300],
        [-0.3900, -0.8000, -0.5400]])

In [16]:
def softmax(z):
    return (torch.exp(z.t()) / torch.sum(torch.exp(z), dim=1)).t()

smax = softmax(Z)
print('softmax:\n', smax)


softmax:
 tensor([[0.4054, 0.3003, 0.2943],
        [0.3523, 0.3893, 0.2584],
        [0.3705, 0.3352, 0.2943],
        [0.3961, 0.2629, 0.3410]])


In [17]:
def to_classlabel(z):
    return torch.argmax(z, dim=1)

print('predicted class labels: ', to_classlabel(smax))
print('true class labels: ', to_classlabel(y_enc))

predicted class labels:  tensor([0, 1, 0, 0])
true class labels:  tensor([0, 1, 2, 0])


In [18]:
def cross_entropy(softmax, y_target):
    return - torch.sum(torch.log(softmax) * (y_target), dim=1)

In [19]:
cross_entropy(smax, y_enc)

tensor([0.9030, 0.9433, 1.2230, 0.9260])